ratings:
  namespace: student26-bookinfo-${{ env.ENV_NAME }}
  image: ghcr.io/jeongchedah/bookinfo-ratings
  tag: ${{ env.ENV_NAME }}
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-${{ env.ENV_NAME }}-ratings-mongodb-secret
ingress:
  host: bookinfo.opsta.net
  path: "/student26/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-${{ env.ENV_NAME }}-ratings-mongodb:27017/ratings
  COMMIT_SHA: CHANGEME